# Generated by Django 5.2.1 on 2025-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_farmerorder_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
    ]
